
[.preface]
== PREFACE

*Historical development of the Standards*: During the International Congress of Surveyors (FIG) at Wiesbaden in 1971, a Working Group (WG) was formed by Commission IV (Hydrography) to develop International Standards of Competence within the profession of surveying at sea. In 1972, during the International Hydrographic Conference in Monaco, the International Hydrographic Organization (IHO) set up a working group for the compilation of training programmes in Hydrography conducted by Member States. In 1974, at the XIV FIG Congress in Washington, it was resolved that the FIG and IHO working groups combine to study and modify the Report of the FIG working group on Educational Standards.

The Report of the joint FIG-IHO WG was accepted by the two parent bodies at their respective conferences in 1977. In consequence of similar resolutions passed at these conferences an FIG/IHO International Advisory Board on Standards of Competence for Hydrographic Surveyors (the Board) was formed.

The Board met annually and compiled and regularly updated "Standards of Competence for Hydrographic Surveyors" (the Standards). The intention of the Board in preparing these Standards was to provide guidance whereby individual surveyors may be trained and qualified in accordance with internationally accepted levels of competence.

*Standards of Competence for Nautical Cartographers*: At the IHO Second Extraordinary Conference in March 2000 the development of a set of Standards of Competence for Nautical Cartographers was approved. It was agreed that the Board would be the appropriate body to lead the preparation of these Standards, with the contribution of the International Cartographic Association (ICA).

The Board therefore changed its name to the FIG/IHO/ICA International Advisory Board on Standards of Competence for Hydrographic Surveyors and Nautical Cartographers. The Board comprises ten (10) Members representing the three parent organizations: FIG (4); IHO (4); and ICA (2). The Secretariat is provided by the IHO Secretariat. In 2009 the name of the Board was changed to _FIG/IHO/ICA International Board on Standards of Competence for Hydrographic Surveyors and Nautical Cartographers (IBSC)_.

*Standards Development*: The Standards are known as S-5 describing the competencies for hydrographic surveyors and S-8 describing the competencies for nautical cartographers. They indicate the minimum degree of knowledge and experience considered necessary for hydrographic surveyors and nautical cartographers, and provide a set of programme outlines against which the Board may evaluate programmes submitted for recognition. In 2008 the recognition period of programmes which had been ten (10) years was reduced to six (6) years, with a transitional period for the existing programmes.

Both Standards recognize two levels of programme: Category "A" and Category "B". In the hydrographic community, Category "A" programmes offer levels of comprehensive and broad-based knowledge in all aspects of the theory and practice of hydrography and nautical cartography. Category "B" programmes provide a level of practical comprehension, along with the essential theoretical background, necessary for individuals to carry out the various hydrographic surveying and nautical cartography tasks.

Earlier editions of the Standards were structured so that Category "B" programmes provided technical education to support a set of fundamental and practical competencies. Initially, Category "A" educational programmes included all Category "B" competencies plus additional detailed-level competencies. This meant that Category "B" was a subset of Category "A".

Since its inception the Board has developed and published eleven (11) editions of the S-5 and three (3) editions of the S-8. These editions reflect the significant scientific and technological developments in the fields of hydrography and cartography, and include considerable improvements in the submission, delivery and review procedures of the programmes. In 2011, a fee was introduced for all submissions.

*Separation of Category "A" and Category "B"*: It became evident to the IBSC that there were influencing factors that brought to the fore a number of imperatives for change in the way hydrographic surveyors and nautical cartographers are educated. To adapt to these new challenges, methodologies, equipment and software, the Board agreed on the separation of Category "A" and Category "B" requirements and a future separate path of development for each category. The motivation behind the separation of the Category "A" and Category "B" requirements and the intended outcome of Category "A" and Category "B" education/training is as follows:

A Category "A" programme will introduce subjects from the beginning at the underlying principles level. A Category "B" programme will introduce subjects from a practical level. According to the above framework the Category "B" Standard is aimed at the _basic educational and training_ requirements for hydrographic technicians and hydrographic surveyors (S-5), and nautical cartographers (S-8). The Category "A" Standard is aimed at the _theoretical educational and foundational background_ necessary for hydrographic surveyors/nautical cartographers in-charge and hydrographic/cartographic managers who will develop specifications for surveys and charts, establish quality control and quality assurance systems and respond to the specific requirements of a full range of hydrographic and/or cartographic projects.

For both Category "A" and Category "B" Standards, the ability to conduct or operate hydrographic surveys in the field or utilize hydrographic and/or cartographic databases to compile and produce charts are essential competencies, and thus a key part of education and training through the necessity of field and applied work (practical exercises and final project).

The educational process itself is in turn influenced by changing technological and methodological imperatives. Connectivity and the introduction of so-called e-learning methods and blended learning techniques, have naturally attracted the attention of the professional community. Another relevant issue is the educational approach in the development of the standards relating to the principles of the style in which the requirements are presented. The IBSC adopted the concept and principles of _constructive alignment_ that are used in most academic institutions and are documented in educational texts, for example Biggs and Tang, Teaching for Quality Learning at University, Open University Press (3rd Edition, 2007). The Standards describe _Intended Learning Outcomes_ (ILO's) using verbs that are detailed under Bloom's taxonomy. In principle, an institution will evaluate students to ensure that they have achieved each learning outcome.

The separation of Category "A" and Category "B" Standards in addition to the adoption of constructive alignment approach was approved in 2012.

Options have been removed from the Standards. The philosophy of the Standards is to develop a hydrographer or nautical cartographer who can work with competence across the full spectrum of the profession. Therefore, the core content within the previous options is considered necessary for all hydrographers and nautical cartographers and can no longer be considered optional. In defining competencies in terms of ILO's, the opportunity exists for institutions to focus attention on specific issues while adhering to competencies and associated content as described in the Standards. Thus, while core competencies are retained, institutions can offer unique programmes within this framework, directed towards specific needs.

*Synopsis*: All components of the hydrographic surveying and nautical cartography professions face challenges as to how best to ensure the continuance of the high standards and how best to ensure the continuation of world-wide best practices based on minimum standards of competence. The IBSC believes that the present editions of the Standards will serve the purpose and will deliver authoritative guidance to the pertinent institutions around the world to prepare, submit and deliver programmes that will be to the benefit of the international hydrographic community.
