
[[data_compression]]
== Data Compression

[[data_compression_overview]]
=== Overview

An ENC file will, because of its structure, contain repeating patterns of information. Examples of this are the consecutive numbering of the feature object identifier (FOID) or small variations in the co-ordinate information within an ENC file. ENC data therefore responds well to compression with reductions in size of between 30% and 60% reducing greatly the cost of transfer of ENC data to its final destination. Only the ENC files (base and update) are compressed. The ENC files are always compressed before they are encrypted as the effectiveness of any compression algorithm relies on the existence of structured data contents.

[[compression_algorithm]]
=== Compression Algorithm

The security scheme uses the ZIP algorithm {blank}footnote:[http://en.wikipedia.org/wiki/ZIP_%28file_format%29] <<zip_ffs,[5]>> to compress and uncompress ENC data. It is identical to the algorithm used in many commercial applications e.g. WinZip, PKZIP. Potential Data Servers and OEMs should be aware that in the past errors have occurred when Data Servers compress data and it is interpreted by popular implementations of the ZIP algorithm as "text" data. If the data is uncompressed with incorrect parameters it can corrupt the ENC file leading to failing integrity checks. Data Servers and OEMs are advised to carefully implement compression/un-compression within their systems.

[[compressed_files]]
=== Compressed Files

The security scheme compresses only the ENC base cell and update files. No other files within the S-57 Exchange Set will be compressed.