
[[data_encryption]]
== Data Encryption

[[what_data_is_encrypted]]
=== What Data is encrypted?

Only one encryption algorithm is used within the Scheme. Only the data within the ENC Base or Update Cell files inside an S-57 Exchange Set, i.e. text or image files are left unencrypted. The scheme encrypts the complete content of the ENC Base or Update data files. Other information within the Scheme that is encrypted includes the OEM System HW_ID which is encrypted and provided to the Data Client in the form of a userpermit.

The cell keys used to encrypt the ENC data files are themselves encrypted by the Data Server and supplied to Data Clients as cell permits. Information about the encryption algorithm is available in <<blowfish>>.

[[how_is_it_encrypted]]
=== How is it encrypted?

Each single ENC cell file is encrypted using a unique Cell Key. The same Cell Key is used to encrypt all updates issued for the cell. The scheme however, allows for the cell keys to be incremented and changed at the discretion of the Data Server. The Cell Keys are delivered to Data Clients in the form of cell permits.

[[encryption_of_enc_info]]
==== Encryption of ENC Information

The ENC information (base cells and updates) are encrypted using a 40-bit key.

[[encryption_of_other_protection_scheme_info]]
==== Encryption of Other Protection Scheme Information

The Userpermit and the Cell permit contents are encrypted using a 48-bit key.

[[blowfish]]
==== Encryption Algorithm – Blowfish

The scheme encrypts all information referenced in <<what_data_is_encrypted>> using the Blowfish algorithm [9]. The algorithm is unpatented and available in the public domain ( http://www.counterpane.com/[www.counterpane.com]). Blowfish is a block cipher algorithm that operates on 64 bit (8 byte) quantities. It requires that the data sources must be padded if they are not a multiple of 8 bytes. The protection scheme uses the "DES in CBC Mode" padding algorithm defined in [8] whenever any data sources must be padded. This complies with the ECB (Electronic Code Book) mode of DES [7].