= Metanorma-IHO sample documents

image:https://github.com/metanorma/mn-samples-iho/workflows/generate/badge.svg["Build Status", link="https://github.com/metanorma/mn-samples-iho/actions?query=workflow%3Agenerate"]
image:https://github.com/metanorma/mn-samples-iho/workflows/docker/badge.svg["Docker Build Status", link="https://github.com/metanorma/mn-samples-iho/actions?query=workflow%3Adocker"]

== Purpose

This repository provides Metanorma-IHO documents in sample form.

== Access

Documents in this repository are available through the deployed mini-site:

* https://metanorma.github.io/mn-samples-iho/[Metanorma-IHO documents]



== References for authoring Metanorma IHO documents

This repository also contains references relating to authoring IHO documents, including:

* At least one document per supported IHO "Serie" (B, S)
** B-12 "`Guidance on Crowdsourced Bathymetry`"
** S-63 "`IHO Data Protection Scheme`", Edition 1.2.1, March 2020

NOTE: These documents are publicly available on the https://iho.int/en/standards-in-force[IHO website]

== Importance of samples

As per the IHO Secretariat, the importance of the samples are as follows:

* C-17 is top of the list
* C-51 is second
* S-51 and M-1
* S-102 and B-12
* New edition of S-44
* S-5 A and S-5 B
* B-6 for multilingual
