
[[cmfp-complex-multidisciplinary-field-project]]
== CMFP: COMPLEX MULTIDISCIPLINARY FIELD PROJECT

Programmes must include a supervised and evaluated Complex Multidisciplinary Field Project with a minimum aggregate period of at *least four weeks*; see "`GUIDELINES FOR THE IMPLEMENTATION OF THE STANDARDS OF COMPETENCE FOR HYDROGRAPHIC SURVEYORS AND NAUTICAL CARTOGRAPHERS`".

The Complex Multidisciplinary Field Project for Category "A" level shall comprise a comprehensive field survey incorporating different aspects of hydrography in a complex environment with varying sea-floor and oceanographic conditions.

Students should undertake:

* Survey specification and planning;
* Hydrographic and oceanographic measurements using a comprehensive suite of instruments;
* Data processing, quality control and quality assurance;
* Preparation of different type of product deliverables and reports.

NOTE: The Complex Multidisciplinary Field Project does not include the practical exercises that form a part of the course modules syllabi and are designed to complement the theory component.
