
[[introduction]]
== Introduction

=== Purpose and Scope

The purpose of this document is to provide guidance to mariners to help them collect and contribute
crowdsourced bathymetric data in a format that is useful to the broadest possible audience. It is hoped
that this document will help mariners optimise data collection, and will provide them with information
about devices, techniques and formats that are recommended by the International Hydrographic
Organization for gathering and contributing CSB data.

This document also provides information about data uncertainty, to help data collectors and data users
better understand quality, completeness, and accuracy issues with crowdsourced bathymetry. Additional
considerations related to crowdsourced bathymetric data logging and data sharing are also briefly
explored.

This document is not intended to provide definitive guidance on how best to use crowdsourced data, as
the scope of CSB is far-reaching and has many potential future applications.

=== Target Audience

The IHO seeks to inform and guide collectors of crowdsourced bathymetry data. Organizations (also
referred to as 'Trusted Nodes') interested in serving as liaisons between data collectors and the IHO may
also find the information helpful. Users of crowdsourced bathymetry data may find this document
informative, as well, although they are not the primary audience.

=== Document Structure

This document addresses several topics related to crowdsourced bathymetry. <<data-contribution>>, "`Data Contribution`" provides information about how to send crowdsourced bathymetry to the IHO Data Centre
for Digital Bathymetry (DCDB), via Trusted Nodes.

<<data-collection>>, "`Data Collection`" provides a high-level overview of the sensors necessary for collecting
crowdsourced bathymetry, as well as best practices and recommendations for collecting CSB.
<<data-and-metadata>>, "`Data and Metadata`" describes the importance of data and metadata, and details the information
that is required for submitting CSB to the DCDB, as well as additional information that should be collected
whenever possible.

<<uncertainty>>, "`Uncertainty`", delves into data quality issues, and discusses how mariners and end users
can better understand the impact of various factors on the reliability of a dataset.
<<additional-considerations>>, "`Additional Considerations`", discusses issues that collectors and
Trusted Nodes may wish to consider before engaging in CSB activities.

Additional detail and further reading are provided via <<annex-abbreviations>> "`Abbreviations`" and external links. This guidance document is intended to be a living document and will be updated in light of further experience and feedback from data collectors and data users.

