
[[additional-considerations]]
== Additional Considerations

NOTE: The following notes, which are not exhaustive, are intended for information only.

The principles of the IHO crowdsourced bathymetry (CSB) programme are similar to many other initiatives where environmental data and information are collected on a voluntary basis by users and the public, and provided under an open data licensing infrastructure in the interests of the common good. In particular, the collection and forwarding of bathymetric data by mariners as part of "`passage sounding`" in support of global initiatives such as the GEBCO project has been taking place for more than a century without issue. Since charts were first produced, mariners have noted and highlighted any inconsistencies with published data, identified during their passage, in the form of a Hydrographic Note. This CSB guidance document is designed to assist the mariner with improving the quality and consistency of any information they may wish to contribute to the public domain.

When considering participation in the IHO CSB programme, mariners should consider the following:

* Mariners proposing to collect bathymetric data as a "`passage sounding`" activity need to be aware of conditions that may be associated with collecting such environmental information within waters of national jurisdiction;
* Those involved in the IHO CSB programme, whether as a data collector, a trusted node or a user, need to be aware of the conditions of the licensing regime under which the bathymetric data will be made available;
* Those using data obtained from the IHO DCDB need to consider the nature and the uncertainty of the data and whether it is fit for the purposes intended.

In order for users to be clear on their rights and obligations while using these data, the IHO CSB Programme has selected a set of licenses from the Creative Commons. The IHO CSB Programme operates under the Creative Commons licensing framework (link:http://www.creativecommons.org/[www.creativecommons.org]). Data supplied to the IHO DCDB by vessels, either directly or through Trusted Nodes, is licenced in accordance with the "`Attribution 4.0 International`" license (CC BY 4.0) (https://creativecommons.org/licenses/by/4.0/), and the "`Attribution 3.0 IGO`" license (CC BY 3.0 IGO) (https://creativecommons.org/licenses/by/3.0/igo/). The IHO may, in the future, update its selected licenses as the versions and terms of the Creative Commons licenses change. However, the IHO will maintain at least the rights currently provided by the CC BY 4.0 and the CC BY-IGO 3.0 licenses.

CSB collectors, including Trusted Nodes and the DCDB, are expected to acknowledge that by providing their data for inclusion in the IHO DCDB database, they are doing so in good faith and for the purpose of increasing bathymetric knowledge of the world's seas, oceans and waterways. If the bathymetric data is provided to the IHO by a CSB collector, then the free-use of the data granted by the data collector should
apply. They also acknowledge that the IHO may allow anyone to copy and redistribute the data that they supply to the IHO DCDB in any medium or format and may remix, transform, and build upon the data for any purpose. CSB collectors cannot revoke these freedoms so long as users of their data follow the licensing terms stated above.

The IHO will also make it clear that that data is being made available on a "`user-beware`" basis; in particular, emphasizing that the user must carefully consider the nature and the uncertainty of the data being used in relation to any use proposed by the user.

In granting its licence to data users, it should be noted that the IHO, as an intergovernmental organization, enjoys certain rights and privileges, which include immunity from the jurisdiction of national courts.
