
[[annex-guidelines-quality-management]]
[appendix]
== GUIDELINES FOR QUALITY MANAGEMENT

NOTE: This annex is *not* an integral part of the S-44 Standards and will be removed when the information therein is fully incorporated into IHO Publication C-13, _Manual on Hydrography_.

*Quality control*: Quality evaluation procedure for maintaining standards in products by testing the output against the specification.


=== Quality Control

Quality control requires more than proving that the end results of the survey are within the required limits stated in the S-44. To achieve the required quality there are three important fields affecting the quality: Material, Procedures, and Personnel. All fields are essential for the quality control of the hydrographic products. Quality control is not just about figures and computations; rather it is a complete overview of all factors affecting the survey.


=== Equipment

The equipment in use must be capable of producing data that meets the required standards. First, the total propagated uncertainties of all equipment and corrections used to derive the reported surveyed value must be included. The temporal and spatial influence of the medium, in which measurements take place, must be considered in this <<def-tpu,total propagated uncertainty>> calculation. By an a priori calculation of the <<def-tpu,total propagated uncertainty>> in a certain environment, it can be determined if the instrumental setup is sufficient for the required quality. If uncertainties cannot be calculated prior to the survey, an alternative methodology of describing the achieved uncertainties must be undertaken to verify that the required standards will be met.

Secondly, the equipment in use should be free of (<<def-systematic_error,systematic>>) <<def-error,errors>> which must be determined by calibration and qualification.

The use of calibrated equipment that can achieve the required data quality is the first step for the quality control process. It is preferred to check the entire system in real conditions (in situ) before surveying, and every time a doubt occurs during the survey.


=== Procedures

Using standardised procedures for hydrographic data collection and processing can reduce the risk of <<def-error,errors>>. By describing the total of procedures, it is possible to incorporate checks and tests on <<def-error,errors>> that occur in an early stage of the process. This is important for <<def-error,errors>> that cannot be detected afterwards.

Procedures may involve complete flow schedules that can be used for external auditing and standardised data products. In the procedures, the a posteriori quality checks must be admitted.


=== Personnel

All survey work must be performed by qualified personnel. The personnel must be trained and capable. Formal qualifications, such as from CAT A and B accredited courses are preferred, but proven working experience may be sufficient. Personal professional accreditation schemes should also be considered.
